preset: recommended
risky: true
enabled:
  - long_array_syntax
  - strict
  - unalign_double_arrow
disabled:
  - align_double_arrow
  - short_array_syntax
finder:
  exclude:
    - modules
    - node_modules
    - storage
    - vendor
    - tests
  name:
    - "*.php"
  not-name:
    - "*.blade.php"
  not-contains:
    - "config"
  not-path:
    - "libraries"
  depth:
    - "< 3"
