                  <th class="text-center">@lang('call.actions')</th>
                  <th class="text-center">@lang('call.internal_expedient')</th>
                  <th class="text-center">@lang('call.priority')</th>
                  <th class="text-center">@lang('call.client')</th>
                  <th class="hidden-xs hidden-sm text-center">@lang('call.observations')</th>
                  <th class="text-center">@lang('call.status')</th>
                  <th class="text-center">@lang('call.operation')</th>
                  <th class="text-center">@lang('call.attended')</th>
                  <th class="text-center">@lang('call.hour')</th>
