                  <th class="text-center active">Expediente</th>
                  <th class="text-center active">Nombre</th>
                  <th class="text-center">Documentos</th>
                  <th class="text-center">Cierre de contrato</th>
                  <th class="text-center">Bitácora de visitas y llamadas</th>
                  <th class="text-center">Contráto de compra venta</th>
                  <th class="text-center">Notaría</th>
                  <th class="text-center">Firma</th>
                  <th class="text-center danger">Acciones</th>
